CREATE DATABASE IF NOT EXISTS learning_plan DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE learning_plan;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sys_op_log;
DROP TABLE IF EXISTS points_ledger;
DROP TABLE IF EXISTS redemptions;
DROP TABLE IF EXISTS rewards;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS parent_children;
DROP TABLE IF EXISTS sys_role_menu;
DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_menu;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password_hash VARCHAR(255) NOT NULL COMMENT '密码哈希',
  display_name VARCHAR(100) NOT NULL COMMENT '显示名',
  phone VARCHAR(30) UNIQUE COMMENT '手机号',
  points INT NOT NULL DEFAULT 0 COMMENT '积分',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  last_login_at DATETIME NULL COMMENT '最近登录时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE roles (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(50) NOT NULL UNIQUE COMMENT '角色编码',
  name VARCHAR(100) NOT NULL COMMENT '角色名称',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

CREATE TABLE sys_menu (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父级ID',
  name VARCHAR(100) NOT NULL COMMENT '菜单名称',
  path VARCHAR(255) COMMENT '路由路径',
  component VARCHAR(255) COMMENT '组件路径',
  type INT NOT NULL COMMENT '类型：1目录/2菜单/3按钮',
  permission VARCHAR(100) COMMENT '权限标识',
  icon VARCHAR(50) COMMENT '图标',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序',
  visible TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可见',
  cache TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否缓存',
  is_frame TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否外链',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统菜单表';

CREATE TABLE sys_user_role (
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE sys_role_menu (
  role_id BIGINT NOT NULL COMMENT '角色ID',
  menu_id BIGINT NOT NULL COMMENT '菜单ID',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (role_id, menu_id),
  CONSTRAINT fk_sys_role_menu_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  CONSTRAINT fk_sys_role_menu_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色菜单关联表';

CREATE TABLE parent_children (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  parent_id BIGINT NOT NULL COMMENT '家长ID',
  child_id BIGINT NOT NULL COMMENT '孩子ID',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uq_parent_child (parent_id, child_id),
  CONSTRAINT fk_parent_child_parent FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_parent_child_child FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='家长孩子关系表';

CREATE TABLE tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  parent_id BIGINT NOT NULL COMMENT '家长ID',
  child_id BIGINT NOT NULL COMMENT '孩子ID',
  title VARCHAR(255) NOT NULL COMMENT '任务标题',
  description VARCHAR(1000) COMMENT '任务描述',
  points INT NOT NULL DEFAULT 0 COMMENT '积分',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态：待完成/已完成',
  submitted_at DATETIME NULL COMMENT '提交时间',
  completed_at DATETIME NULL COMMENT '完成时间',
  checkin_note VARCHAR(500) COMMENT '打卡备注',
  checkin_images VARCHAR(2000) COMMENT '打卡图片（逗号分隔）',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_task_parent FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_task_child FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务表';

CREATE TABLE rewards (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  parent_id BIGINT NOT NULL COMMENT '家长ID',
  name VARCHAR(255) NOT NULL COMMENT '奖励名称',
  description VARCHAR(1000) COMMENT '奖励描述',
  points_cost INT NOT NULL DEFAULT 0 COMMENT '所需积分',
  stock INT NOT NULL DEFAULT 0 COMMENT '库存',
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '奖励状态：启用/停用',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_reward_parent FOREIGN KEY (parent_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='奖励表';

CREATE TABLE redemptions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  reward_id BIGINT NOT NULL COMMENT '奖励ID',
  child_id BIGINT NOT NULL COMMENT '孩子ID',
  points_cost INT NOT NULL COMMENT '消耗积分',
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '兑换状态：待审核/已同意/已拒绝',
  redeemed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '兑换时间',
  review_note VARCHAR(500) COMMENT '审核备注',
  reviewed_at DATETIME NULL COMMENT '审核时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_redemption_reward FOREIGN KEY (reward_id) REFERENCES rewards(id) ON DELETE CASCADE,
  CONSTRAINT fk_redemption_child FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='兑换记录表';

CREATE TABLE points_ledger (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  child_id BIGINT NOT NULL COMMENT '孩子ID',
  points INT NOT NULL COMMENT '积分',
  type VARCHAR(20) NOT NULL COMMENT '积分类型：获得/消耗',
  ref_type VARCHAR(20) NOT NULL COMMENT '积分来源：任务/奖励',
  ref_id BIGINT NULL COMMENT '来源ID',
  note VARCHAR(255) COMMENT '备注',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  CONSTRAINT fk_points_child FOREIGN KEY (child_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='积分流水表';

CREATE TABLE sys_op_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT COMMENT '用户ID',
  username VARCHAR(100) COMMENT '用户名',
  role_codes VARCHAR(200) COMMENT '角色编码',
  method VARCHAR(10) COMMENT '请求方法',
  path VARCHAR(255) COMMENT '请求路径',
  status_code INT COMMENT '响应状态码',
  error_message VARCHAR(1000) COMMENT '错误信息',
  request_body TEXT COMMENT '请求体',
  response_body TEXT COMMENT '响应体',
  query_params VARCHAR(1000) COMMENT '查询参数',
  ip VARCHAR(64) COMMENT 'IP地址',
  user_agent VARCHAR(255) COMMENT '浏览器标识',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';

SET FOREIGN_KEY_CHECKS = 1;